version: '2'
services:
  neo4j-wiki:
    build: ./infrastructure/neo4j
    image: neotest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo

  nodejs:
    build:
        context: .
        dockerfile: Dockerfile-node
    depends_on:
      - neo4j-wiki
    image: nodetest
    links:
      - neo4j-wiki:neoAlias
    ports:
      - "8080:8080"
    restart: always
    environment:
      ENV_NEO4J_HOST: neoAlias
     #ENV_NEO4J_PW: neo4j
