version: '2'
services:

  neo4j-wiki:
    build:
      context: ./infrastructure/neo4j
      args:
        wikilanguage: bar
    image: neo-wiki-img
    restart: always
    ports:
      - "7474"
      - "7687"
    environment:
      NEO4J_AUTH: neo4j/neo

  arango-wiki:
    build: ./infrastructure/arangodb
    image: arango-wiki-img
    restart: always
    ports:
      - "8529"
    environment:
      ARANGO_ROOT_PASSWORD: arango # does not show effect, since we import a db dump with users.

  php-wiki:
    build: .
    depends_on:
      - neo4j-wiki
      - arango-wiki
    image: phptest
    links:
      - neo4j-wiki:neoAlias
      - arango-wiki:arangoAlias
    ports:
      - "80"
    restart: always
    environment:
      USER_NEO: neo4j
      PWD_NEO: neo
      HOST_NEO: neoAlias
      HOST_ARANGO: arangoAlias
      #PWD_ARANGO: arango
