version: '2'
services:

  neo4j-wiki:
    build:
      context: ./infrastructure/neo4j
      args:
        wikilanguage: bar
    image: neotest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"

  arango-wiki:
    build: ./infrastructure/arangodb
    image: arangotest
    restart: always
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: arango

  my_application:
    build: .

    depends_on:
      - neo4j-wiki
    image: phptest
    links:
      - neo4j-wiki:neoAlias
      - arango-wiki:arangoAlias
    ports:
      - "80:80"
    restart: always
    environment:
      USER_NEO: neo4j
      PWD_NEO: neo
      HOST_NEO: neoAlias
      HOST_ARANGO: arangoAlias
      PWD_ARANGO: arango

