#docker exec -i -t 6 /bin/bash
#docker run -p 80 -e USER_NEO='neo4j' -e PWD_NEO="neo" -e HOST_NEO="localhost" -e PORT_NEO="7687" phptest

version: '2'
services:
  neo4j-wiki:
    image: neotest
    restart: always
    ports:
      - "7474:7474" #zweite Zahl weg, wenn dynamisch!
      - "7687:7687"
  my_application:
    build: .
    depends_on:
      - neo4j-wiki
    image: phptest
    links:
      - neo4j-wiki:neoAlias
    ports:
      - "80"
    restart: always
    environment:
      USER_NEO: neo4j
      PWD_NEO: neo
      HOST_NEO: neoAlias
